site_name: Rephi
site_description: "Rephi — чистый функциональный язык на C с ленивыми вычислениями и graph-reduction"
site_author: Artem

docs_dir: docs_src
site_dir: docs

theme:
  name: readthedocs
  language: ru
  palette:
    scheme: default
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  icon:
    repo: fontawesome/brands/github

nav:
  - Главная: index.md
  - Установка: installation.md
  - Быстрый старт: quickstart.md
  - Синтаксис: syntax.md
  - Архитектура: architecture.md
  - Стандартная библиотека: stdlib.md
  - Примеры: examples.md

plugins:
  - search

markdown_extensions:
  - toc:
      permalink: true
