site_name: Rephi
site_description: «Rephi» — чистый функциональный язык на C с ленивыми вычислениями и graph-reduction
site_author: Ваше имя
repo_url: https://github.com/MAILabs-Education-2025/fp-compiler-coursework-rephi
theme:
  name: material
nav:
  - Home: index.md
  - Установка: installation.md
  - Быстрый старт: quickstart.md
  - Синтаксис: syntax.md
  - Архитектура: architecture.md
  - Стандартная библиотека: stdlib.md
  - Примеры: examples.md
 
